scripts/generate-service.sh
template/Service.swift_template
template/ServiceTests.swift_template
template/service.podspec

Classes need to start with capital letter. 
Allow to specify SDK name using small letter but also provide class name as capital.

Add class name to generator

---

modules/core/agscore.podspec

https://issues.jboss.org/browse/AGIOS-647

Adjust version ranges for dependencies

---

README.md
docs/metrics/README.adoc
example/AeroGearSdkExample/AppDelegate.swift
example/AeroGearSdkExample/Info.plist
modules/metrics/AgsMetrics.swift
modules/metrics/MetricsContainer.swift
modules/metrics/metrics/PlatformMetrics.swift
modules/metrics/metrics/StartupMetrics.swift

Adjust metrics to new requirements from proposal

---

modules/core/config/MobileConfig.swift
modules/core/config/ServiceConfig.swift

Change structures to be immutable.

Make configuration immutable

---

docs/auth/README.adoc
docs/service-guide.adoc
example/AeroGearSdkExample.xcodeproj/project.pbxproj
example/AeroGearSdkExample.xcodeproj/xcshareddata/xcschemes/AeroGearSdkExample.xcscheme
example/AeroGearSdkExampleTests/auth/AuthTests.swift
example/Podfile
modules/auth/AgsAuth.swift
modules/auth/User.swift
modules/auth/agsauth.podspec
modules/auth/authenticator/Authenticator.swift
modules/auth/authenticator/OIDCAuthenticator.swift
modules/auth/config/AuthenticationConfig.swift
modules/auth/config/KeycloakConfig.swift
modules/auth/credentials/CredentialsManager.swift
modules/auth/credentials/OIDCCredentials.swift
modules/core/config/ServiceConfig.swift
modules/core/metrics/metrics/AppMetrics.swift
modules/core/metrics/metrics/DeviceMetrics.swift

https://issues.jboss.org/browse/AEROGEAR-2086
Create some of the base classes/interfaces for the iOS IDM SDK based on the android one.
Please see commit ca691d9. The other one is auto generated by swiftlint.
ping @aidenkeating @rachael-oregan @ziccardi could you take a look at this PR if you are planning on the ios IDM SDK. We will chat about it during the standup today.

[WIP] Idm sdk base

---

README.md
docs/core/README.adoc
docs/metrics/README.adoc
docs/metrics/extending-metrics.adoc
modules/core/metrics/impl/AppMetrics.swift

Documentation updates for metrics

AGIOS-653 - documentation for metrics

---

docs/metrics/README.adoc

Remove contributor guide link from metrics user guide doc.

Remove link to metrics contributor guide

---

docs/auth/sso.adoc

We need a document for SSO on iOS.
JIRA: [https://issues.jboss.org/browse/AEROGEAR-2129]
Add a documentation for SSO on iOS

 📝 doc: add doc for SSO

---

example/AeroGearSdkExample/auth/AuthDetailsViewController.swift

The user details view is not updated when I tried to login twice with different users
Make sure the user detail view is updated when the user model is changed.

 🐛 fix: make sure the user details view is updated

---

docs/auth/README.adoc

Demo videos in docs are good
Added demo video to the auth getting started docs

add demo video to docs

---

example/AeroGearSdkExample/mobile-services.json
example/AeroGearSdkExample/push/PushHelper.swift
example/AeroGearSdkExample/push/PushViewController.swift

Allow to dismiss notification dialog (receive more than one notification)
Change example config to production.

Allow to dissmiss notification dialog

---

example/AeroGearSdkExample.xcodeproj/project.pbxproj
example/AeroGearSdkExample.xcodeproj/xcshareddata/xcschemes/AeroGearSdkExampleTests.xcscheme
example/AeroGearSdkExample/mobile-services.json
example/AeroGearSdkExample/push/PushHelper.swift
example/AeroGearSdkExampleIntegrationTests/metrics/MetricsIntegrationTests.swift
example/AeroGearSdkExampleTests/AgPushTests.swift
example/AeroGearSdkExampleTests/mocks/MockCredentialManager.swift
modules/auth/User.swift
modules/auth/authenticator/OIDCAuthenticator.swift
modules/core/http/AgsHttpResponse.swift
modules/core/metrics/engine/MetricsPublisher.swift
modules/push/AgsPush.swift

Related issues:
* [AGIOS-680](https://issues.jboss.org/browse/AGIOS-680)

Read credentials from mobile-services.json

---

example/AeroGearSdkExample/push/PushViewController.swift
example/AeroGearSdkExample/push/push.storyboard

Show list view with sent push notifications the same as it happens on Android.

Add list view to Push Notification screen

---

modules/core/metrics/AgsMetrics.swift
modules/core/metrics/MetricsPublishable.swift
modules/core/metrics/engine/MetricsPublisher.swift

Adjust format of the metrics to new requirements
https://issues.jboss.org/browse/AGIOS-683
There is no security checks implementation for IOS SDK. 
So I could not test that with the full payload.

fix: adjust format of the metrics to new requirements

---

example/AeroGearSdkExample.xcodeproj/project.pbxproj
example/AeroGearSdkExampleIntegrationTests/metrics/MetricsIntegrationTests.swift
example/AeroGearSdkExampleTests/core/MetricsServiceTests.swift

Fix for integration test due to changes in https://github.com/aerogear/aerogear-ios-sdk/pull/77
* metrics integration test fix + deletion of invalid test
* enabling metrics unit tests - the tests were not included in the test suite

fix: integration test, enabling metrics unit test

---

example/AeroGearSdkExample/AppDelegate.swift
example/AeroGearSdkExampleTests/auth/jwt/JwtTests.swift
example/AeroGearSdkExampleTests/core/MetricsServiceTests.swift
example/AeroGearSdkExampleTests/mocks/MockJwk.swift
example/AeroGearSdkExampleTests/performance/SdkStartupPerfTest.swift
modules/auth/AgsAuth.swift
modules/auth/User.swift
modules/auth/jwk/JwksManager.swift
modules/auth/jwt/Jwt.swift
modules/core/AgsCore.swift
modules/core/metrics/AgsMetrics.swift

We forgot to use formatter for code style. 
Run one on the master to make sure that we have the same style, formatting on entire SDK.

fix: formatting issues

---

docs/metrics/extending-metrics.adoc

Minor update to documentation for metrics service

docs: Update documentation

---

modules/core/metrics/impl/AppMetrics.swift

Add additional framework field

AEROGEAR-2699: add native framework field

---

.gitignore
docs/antora.yml
docs/local-site.yml
docs/modules/ROOT/_attributes.adoc
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/_attributes.adoc
docs/modules/ROOT/pages/index.adoc

adding antora structure to validate publishing, will follow up with moving files to populate site

add antora structure

---

.gitignore
README.md
example/README.adoc
scripts/cloneShowcase.sh

Add required scripts, docs etc.

Add showcase script

---

CONTRIBUTING.md
scripts/cloneShowcase.sh

fix: support dev mode

---

AGSSec.podspec
docs/security/README.adoc
example/AeroGearSdkExample.xcodeproj/project.pbxproj
example/AeroGearSdkExampleTests/security/SecurityTests.swift
example/Podfile
modules/auth/User.swift
modules/security/AgsSec.swift
modules/security/SecurityCheck.swift
modules/security/SecurityCheckResult.swift
modules/security/checks/IsEmulatorCheck.swift

[JIRA 1](https://issues.jboss.org/browse/AGDROID-2175) - Creating the base API
[JIRA 2](https://issues.jboss.org/browse/AGDROID-2127) - Implementing the first check
This is an initial to PR to verify that the approach is correct and that the protocols are ok. It has included one security check to show the flow of the code.

AEROGEAR-2175 basic module created and first check

---

docs/security/README.adoc

JIRA: https://issues.jboss.org/browse/AEROGEAR-2119
Documentation on how to use the security self defence checks.  This will need to be updated later once the metrics part is implemented in the SDK.

AEROGEAR-2119 - Security Self Defence Docs

---

scripts/cloneShowcase.sh

Adjust script for the changes in https://github.com/aerogear/aerogear-ios-sdk/pull/115

fix: clone showcase

---

scripts/release.sh

☘️ Forgot to change another value in other script. Ideally we could have one place for those in separate script and source them.

fix: add security SDK to release script

---

docs/push/README.adoc

Found a typo on push readme
JIRA: n/a
Just a fix of the case for the import of the push module
n/a

fixed typo in doc

---

AGSSync.podspec
README.md
modules/auth/AgsAuth.swift
modules/core/metrics/engine/MetricsPublisher.swift
modules/push/AgsPush.swift
modules/security/AgsSecurity.swift
modules/security/deviceTrust/SecurityCheck.swift
modules/security/deviceTrust/SecurityCheckResult.swift
modules/security/deviceTrust/checks/DeviceLockCheck.swift
modules/security/deviceTrust/checks/NonDebugCheck.swift
modules/security/deviceTrust/checks/NonEmulatorCheck.swift
modules/security/deviceTrust/checks/NonJailbrokenCheck.swift
modules/security/metrics/SecurityCheckResultMetric.swift
modules/sync/AgsSync.swift

Sync SDK initial wrapper

---

modules/auth/AgsAuth.swift
modules/auth/AuthHeaderProvider.swift
modules/auth/User.swift
modules/core/http/AgsHttp.swift
modules/sync/AgsSync.swift
modules/sync/InterceptedNetworkTransport.swift

Add ability to extend headers by using header provider. 
Write custom networking in for purpose of sync

Add header providers to SDK

---

modules/auth/AgsAuth.swift
modules/auth/AuthHeaderProvider.swift
modules/core/http/AgsHttp.swift
modules/sync/SyncNetworkTransport.swift

JIRA: [https://issues.jboss.org/browse/AEROGEAR-7853]
A new `currentUser` method has been added accepting the `autoRefresh` parameter.
If the access token needs to be refreshed, it gets refreshed automatically.

Implemented token refresh using performAction
